save_dir: ./saved_models
save_name: npmatch_cifar100_400_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 400
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
alg: npmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10256
dist_backend: nccl
gpu: None
